### ISSUE TITLE
Which version of grain to get this working?

### ISSUE THREAD

**Issue by gmlewis** [grain-lang/lunatic-gr#17]
Hi, I'm trying to duplicate the very cool YouTube demo: https://youtu.be/HdWEA_erA6w?si=CErTVpaHcU1s2O8k&t=363
but am wondering if I am using the wrong version of `grain` since Oscar mentioned "version 0.6 syntax" which I don't know how to get.

Here's what happens with grain 0.5.13 on a Mac M2 Max with `grain` built from source:

```bash
$ grain --version
0.5.13
$ make examples
make hello
grain compile -I . --use-start-section --no-wasm-tail-call --release examples/hello.gr
make net
grain compile -I . --use-start-section --no-wasm-tail-call --release examples/net.gr
File "examples/net.gr", line 4, characters 19-22:
Error: Syntax error after '{' and before 'Net'.
Expected a lowercase identifier to use a value, the keyword `module` followed by an uppercase identifier to use a module, or the keyword `type` followed by an uppercase identifier to use a type.

node:child_process:915
    throw err;
    ^

Error: Command failed: /Users/glenn/src/github.com/grain-lang/grain/cli/bin/grainc.exe --include-dirs . --stdlib /Users/glenn/src/github.com/grain-lang/grain/stdlib --profile=release --no-wasm-tail-call --use-start-section examples/net.gr
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at GrainCommand.execGrainc (/Users/glenn/src/github.com/grain-lang/grain/cli/bin/exec.js:38:10)
    at GrainCommand.listener [as _actionHandler] (/Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:488:17)
    at /Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:1227:65
    at GrainCommand._chainOrCall (/Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:1144:12)
    at GrainCommand._parseCommand (/Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:1227:27)
    at GrainCommand._dispatchSubcommand (/Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:1050:25)
    at GrainCommand._parseCommand (/Users/glenn/src/github.com/grain-lang/grain/node_modules/commander/lib/command.js:1193:19) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 79482,
  stdout: null,
  stderr: null
}
make[1]: *** [net] Error 1
make: *** [examples] Error 2
```

**Comment by phated** [comment]
The example code won't work without updates. See #15 

With some updates, it would work with [Preview](https://grain-lang.org/docs/getting_grain#Previews) builds.

**Comment by gmlewis** [comment]
Thank you, @phated !
